#Compile option define ##############
CC = g++
CXX = g++
AR = ar
LD = ld
ARFLAGS =
CFLAGS = -g -Wall -Wextra -pthread
CXXFLAGS = -g -std=c++11 -Wall -Wextra -pthread
#CFLAGS = -g  -pthread
#CXXFLAGS = -g -std=c++11 -pthread

#Abbrevition  ##############
RM = rm -f


